#!/bin/sh

enabled="$(nvram get 25474)"
server="$(nvram get 25475)"
port="$(nvram get 25476)"

start()
{
    if [ "x${enabled}" = "x1" -a "x${server}" != "x" -a "x${port}" != "x" ]; then
        /usr/bin/telemetryd "${server}" "${port}"
    fi    
}    

stop()
{
    killall telemetryd
}

restart() {
    stop
    start
}

case "${1}" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
esac

exit $?
