#!/bin/sh

if [ -r /tmp/config/rc.conf -a "$conf_sourced" != "1" ]; then
	. /tmp/config/rc.conf
fi

RESOLV_CONF="/tmp/.resolv4.conf"
RESOLV_CONF_PREF="/tmp/.resolv4.conf.pref"

# set default route
route add default gw ${IPREMOTE}

PREFERRED_DNS=0

if [ -n "${wan_preferred_dns1}" -a "${wan_preferred_dns1}" != "..." -a  "${wan_preferred_dns1}" != "0.0.0.0" \
	-a -n "`nvram get 92`" -a "`nvram get 92`" != "0" ]; then
	> ${RESOLV_CONF_PREF}
	PREFERRED_DNS=1
	echo nameserver ${wan_preferred_dns1} >> $RESOLV_CONF_PREF
fi
if [ -n "${wan_preferred_dns2}" -a "${wan_preferred_dns2}" != "..." -a  "${wan_preferred_dns2}" != "0.0.0.0" \
	-a -n "`nvram get 5026`" -a "`nvram get 5026`" != "0" ]; then
	if [ "${PREFERRED_DNS}" = "0" ]; then
		> ${RESOLV_CONF_PREF}
		PREFERRED_DNS=1
	fi
	echo nameserver ${wan_preferred_dns2} >> $RESOLV_CONF_PREF
fi
if [ -n "${wan_preferred_dns3}" -a "${wan_preferred_dns3}" != "..." -a  "${wan_preferred_dns3}" != "0.0.0.0" \
	-a -n "`nvram get 5030`" -a "`nvram get 5030`" != "0" ]; then
	if [ "${PREFERRED_DNS}" = "0" ]; then
		> ${RESOLV_CONF_PREF}
		PREFERRED_DNS=1
	fi
	echo nameserver ${wan_preferred_dns3} >> $RESOLV_CONF_PREF
fi
if [ -n "${wan_preferred_dns4}" -a "${wan_preferred_dns4}" != "..." -a  "${wan_preferred_dns4}" != "0.0.0.0" \
	-a -n "`nvram get 5034`" -a "`nvram get 5034`" != "0" ]; then
	if [ "${PREFERRED_DNS}" = "0" ]; then
		> ${RESOLV_CONF_PREF}
		PREFERRED_DNS=1
	fi
	echo nameserver ${wan_preferred_dns4} >> $RESOLV_CONF_PREF
fi

[ -n "${DNS1}" ] && echo "nameserver ${DNS1}" >> ${RESOLV_CONF}
[ -n "${DNS2}" ] && echo "nameserver ${DNS2}" >> ${RESOLV_CONF}

# if no pref dns configured, just delete the pref file
if [ "${PREFERRED_DNS}" = "0" ]; then
	rm $RESOLV_CONF_PREF
fi

/usr/sbin/merge-hook
echo stop led_error_wan_pppoe > /proc/gxp/led_patterns
echo start led_wan_dhcp_ok > /proc/gxp/led_patterns
