#!/bin/sh

#will wait for a connection to the network before running provision.

IP=
check_wan()
{
	IP=
	WAN="$(nvram get wan_device)"
    #check if device has and ip address
	if [ -n "${WAN}" ]; then
		# Bug 90573
        IP=`ifconfig ${WAN} 2> /dev/null |grep "inet"|sed '/127.0.0.1/ d'|sed '/inet6/ d'|sed '/169.254.1./ d'`
	fi

    if [ -z "${IP}" ]
    then
        # check IPv6 address
        # Bug 90573
        IP=`ifconfig ${WAN} 2> /dev/null |grep "inet"|sed '/127.0.0.1/ d'|sed '/fe80/ d'|sed '/Scope:Host/ d'|sed '/169.254.1./ d'`
	fi

	#check if cable is uplugged
	STATE="$(cat /sys/class/net/eth0/operstate)"
	if [ "${STATE}" = "down" ]; then
		IP=
	fi	
}

check_wan

while [ -z "${IP}" ]
do	
	if [ -z "${IP}" ]; then
		sleep 5
	fi
	check_wan
	nvram set :ini_prov=1
done	

/sbin/provision &
