#!/bin/sh

if [ -r /tmp/config/rc.conf ]; then
    . /tmp/config/rc.conf
fi

stop() {
	killall telnetd >/dev/null 2>&1
}

start() {
# 276 Disable Telnet for HT5XX/7XX
# 276 Disable SSH for HT8XX
# 28120 Disable Telnet for HT8XX
DefaultTelnetPort="23"
[ -z "${telnet_port}" ] && telnet_port="${DefaultTelnetPort}"
if [ "x${FACTORYMODE}" = "x1" -o "${telnet_disable}" = "0" ]; then
	if [ "${sshd_disable}" = "0" -a "${sshd_port}" = "${telnet_port}" ];then
		logger -p kern.err -t "`nvram get syslog_id`" "SSH port(${sshd_port}) conflicts with telnet port(${telnet_port}), disable telnet"
	else
		if [ "${telnet_port}" != "${DefaultTelnetPort}" ];then
			telnetd -l /sbin/gs_config -p ${telnet_port}
		else
			telnetd -l /sbin/gs_config
		fi
	fi
fi
}

restart() {
	stop
	start
}

case "$1" in
start)
	start
	;;
stop)
	stop
	;;
restart)
	restart
	;;
*)
	echo $"Usage $0 {start|stop|restart}"
	exit 1
esac

exit $?

